regression:
	g++ -o main.out regression_main.cpp neural_network.cpp layer.cpp -O3 -larmadillo && ./main.out

classification:
	g++ -o main.out classification_main.cpp neural_network.cpp layer.cpp -O3 -larmadillo && ./main.out
